#Variables
substitutions:
  device_name: socket_4_main_office_desk
  friendly_name: Main Office Desk
  sliding_window_moving_average_window_size: "10"   
  sliding_window_moving_average_send_every: "5"

wifi:
  use_address: 10.25.30.111
  
packages:
  api: !include includes/common_includes/core/core_api.yaml
  logger: !include includes/common_includes/core/core_logger.yaml
  ota: !include includes/common_includes/core/core_ota.yaml
  web_server: !include includes/common_includes/core/core_web_server.yaml
  wifi: !include includes/common_includes/core/core_wifi.yaml
    

# Basic Config
esphome:
  name: "$device_name"
  platform: ESP8266
  board: esp8285
  build_path: ./build/$device_name

output:
#  - platform: gpio # Needs to be out commented otherwise there will be a relay toggle on boot
#    pin: GPIO15
#    id: relay
  - platform: gpio
    pin: GPIO2
    id: led_blue
    inverted: true
  - platform: gpio
    pin: GPIO00
    id: led_red
    inverted: true
    
switch:
  - platform: gpio
    pin: GPIO15
    name: "$friendly_name"
    restore_mode: ALWAYS_ON
    id: relay
    internal: true

binary_sensor:
  - platform: gpio
    pin: GPIO13
    id: button
    internal: true
    on_press:
      then:
        - switch.toggle: relay

sensor:
  - platform: hlw8012
    update_interval: 3s
    change_mode_every: 3
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    power:
      name: "$friendly_name Power"
      unit_of_measurement: W
      id: "power_wattage"
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: $moving_average_window_size
            send_every: $moving_average_sent_every
        - calibrate_linear:
            - 0 -> 0.6
            - 38.892 -> 6.0
            - 66.2 -> 9.6
            - 59.579 -> 8.8
            - 3882.165 -> 512.0
            - 7605.047 -> 1003
            - 12075 -> 1580

    current:
      name: "${friendly_name} Current"
      unit_of_measurement: A
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: $moving_average_window_size
            send_every: $moving_average_sent_every
      internal: true

    voltage:
      name: "$friendly_name Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: $moving_average_window_size
            send_every: $moving_average_sent_every
        - calibrate_linear:
            - 0.0 -> 0.0
            - 756.512 -> 238.0
    internal: true
    
