# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


 # Example configuration.yaml entry for Google Translate TTS service

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://10.25.10.2:8123
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
switch: !include switches.yaml
lifx: !include lifx.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
homekit: !include homekit.yaml
input_select: !include input_selects.yaml
#entity_controller: !include entity_conroller.yaml
#adaptive_lighting: !include adaptive_lighting.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # Add the IP address of the proxy server

zha:
  zigpy_config:
    ota:
      ikea_provider: true                        # Auto update Trådfri devices
      ledvance_provider: false                    # Auto update LEDVANCE devices
      #otau_directory: /path/to/your/ota/folder  # Utilize .ota files to update everything else


# Example configuration.yaml entry
media_player:
  # Use the Python ADB implementation
  - platform: androidtv
    name: WemaxA300
    host: 10.25.90.167
    port: 5555

logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug


recorder:
  db_url: 'sqlite:///:memory:'
  #db_url: !secret mariadb_url
  auto_purge: true
  purge_keep_days: 7
  #exclude:
  #  entity_globs:
  #    - sensor.time*
  #    - sensor.date_*
  #  entities:
  #    - sensor.internet_time

##InfluxDB
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 10
  default_measurement: state
  exclude:
    entity_globs:
      - light.lg_*
      - binary_sensor.*occupancy*
  include:
    domains:
      - weather
      - sun
      - light
      - device_tracker
      - person
      - climate
    entities:
      - sensor.influxdb_db_size
      - sensor.disk_use_percent
      - sensor.last_boot
      - sensor.memory_use
      - sensor.memory_use_percent
      - sensor.processor_temperature
      - sensor.processor_use_percent
    entity_globs:
      - sensor.*battery*
      - sensor.*temperature*
      - sensor.*humidity*
      - sensor.*illuminance*
      - binary_sensor.*motion*
      - sensor.whiterabbit_*
      - sensor.freyas_iphone_*


##Spotify
spotify:
  client_id: 3b6a83360e524564acaac5ccbc0fc187
  client_secret: 4ab09ccc8bb54fb5b7816116ee7ae835      

  ##Octoprint

#octoprint:
#  host: http://10.25.10.15
#  api_key: EF22B285621A4E088E982A498DF949D5
#  name: CR10
#  number_of_tools: 1
#  bed: 1
#  sensors:
#    monitored_conditions:
#      - 'Current State'
#      - 'Job Percentage'
#      - 'Time Elapsed'
#      - 'Time Remaining'
#      - 'Temperatures'

##Counter
counter:
  counter_roomba_living_room:
    name: Roomba Living Roonm runs/day
    icon: mdi:robot-vacuum
  counter_roomba_office:
    name: Roomba Office runs/day
    icon: mdi:robot-vacuum

##Telegram Bot
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_api_key
#    allowed_chat_ids:
#      - !secret telegram_id_max #Maxs
#      - !secret telegram_id_siri #Siri Group
#
###Notify
#notify:
#  - name: Siri@Group
#    platform: telegram
#    chat_id: !secret telegram_id_siri
#  - name: Siri@Max
#    platform: telegram
#    chat_id: !secret telegram_id_max

cover:
  - platform: group
    name: Living Room Shades
    entities:
      - cover.living_room_shade_l
      - cover.living_room_shade_r

  - platform: group
    name: All Shades internal
    entities:
      - cover.living_room_shade_l
      - cover.living_room_shade_r
      - cover.office_shade
      - cover.bedroom_shade

  - platform: group
    name: Front Shades internal
    entities:
      - cover.living_room_shade_l
      - cover.living_room_shade_r
      - cover.office_shade

notify:
  - name: Awsome People
    platform: group
    services:
      - service: mobile_app_freyas_iphone
      - service: mobile_app_whiterabbit

#climate:
#  - platform: smart_thermostat
#    name: Office Heating
#    heater: switch.office_heating_relay
#    target_sensor: sensor.office_temperature_pvvx
#    precision: 0.1
#    min_temp: 16
#    max_temp: 28
#    ac_mode: False
#    target_temp: 19
#    target_temp_step: 0.1
#    keep_alive:
#      seconds: 60
#    away_temp: 16
#    kp : 75 #kp : 75
#    ki : 0.01 #ki : 0.001
#    k d : 70000 #kd : 70000
#    pwm : 00:15:00
#    # Autotune
#    #autotune: "ziegler-nichols"
#    #noiseband: 0.2
#    #lookback: 18:00:00