# Wifi
wifi:
  networks:
  - ssid: !secret wifi_not_ssid
    password: !secret wifi_not_password
  reboot_timeout: 60min
  fast_connect: true

# Access Point
  ap:
    ssid: "${device_name}"
    password: !secret wifi_ap_password

# Captive Portal
captive_portal:

