---
# WiFi Info Text Sensor
#
# The wifi_info text sensor platform exposes different WiFi information via
# text sensors.
#
#
platform: wifi_info
ip_address:
  name: "${friendly_name} IP Address"
ssid:
  name: "${friendly_name} Connected SSID"
bssid:
  name: "${friendly_name} Connected BSSID"
