# Total Daily Enegery

sensor:
  - platform: total_daily_energy
    name: ${friendly_name} Total Daily Energy
    power_id: my_power

  # The power sensor to convert, can be any power sensor
  - platform: hlw8012
    # ...
    power:
      id: my_power

# Enable time component to reset energy at midnight
packages:
  time: !include includes/common_includes/time_sensor.yaml