# WiFi Info Text Sensor
# The wifi_info text sensor platform exposes
# different WiFi information via text sensors.

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address