# Device Specific Config
esphome:
  <<: !include .esphome.yaml
  platform: ESP32
  board: esp32dev

# Example configuration entry for finding
# Service UUIDs and iBeacon UUIDs and identifiers
esp32_ble_tracker:

text_sensor:
  - platform: ble_scanner
    name: "BLE Devices Scanner"
