# Gosund Sp111 Base Confing, Relay defautls to ON.
# If you use this template be aware that different versions of this plug exist.
# I grouped them in the gsheet below.
# https://docs.google.com/spreadsheets/d/1SL-N8V5TfUvrYqx9DcNiYm6hDFtqOX6M2BlFxSOUfBo/edit?usp=sharing


substitutions:
  time_timezone: "Europe/Berlin"

esphome:
  name: "${device_name}"
  build_path: "./.build/${device_name}/"
  platform: ESP8266
  board: esp8285

output:
  - platform: gpio
    pin: GPIO2
    id: led_blue
    inverted: true
  - platform: gpio
    pin: GPIO00
    id: led_red
    inverted: true
    
switch:
  - platform: gpio
    pin: GPIO15
    name: "${friendly_name}"
    restore_mode: ALWAYS_ON
    id: relay

# Light is used instead of status light to keep it off.
light:
  - platform: binary
    name: "${friendly_name} Led Blue"
    output: led_blue
    restore_mode: ALWAYS_OFF
    internal: true
  - platform: binary
    name: "${friendly_name} Led Red"
    output: led_red
    internal: true
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    pin: GPIO13
    id: button
    internal: true
    on_press:
      then:
        - switch.toggle: relay

sensor:
  - platform: hlw8012
    update_interval: 3s
    change_mode_every: 3
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    power:
      device_class: "energy"
      state_class: "measurement"
      name: "${friendly_name} Power"
      unit_of_measurement: W
      id: device_power
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 0 -> 0.6
            - 38.892 -> 6.0
            - 66.2 -> 9.6
            - 59.579 -> 8.8
            - 3882.165 -> 512.0
            - 7605.047 -> 1003
            - 12075 -> 1580
        - sliding_window_moving_average:
           window_size: 15
           send_every: 15
    current:
      device_class: "current"
      state_class: "measurement"
      name: "${friendly_name} Current"
      unit_of_measurement: A
      accuracy_decimals: 1
      filters:
      internal: true
    voltage:
      device_class: "voltage"
      state_class: "measurement"
      name: "${friendly_name} Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 756.512 -> 238.0
      internal: true

  - platform: template
    id: sensor_uptime_timestamp
    name: "${friendly_name} Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state
      );
      return timestamp;
  - platform: uptime
    id: sensor_uptime

  - platform: total_daily_energy
    id: sensor_total_daily_energy
    power_id: device_power
    name: "${friendly_name} Daily Energy Usage"
    unit_of_measurement: "kWh"
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

time:
  - platform: homeassistant
    id: time_homeassistant
    timezone: "${time_timezone}"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

  - platform: sntp
    id: time_sntp
    servers: 
      - $ntp
    timezone: "${time_timezone}"

