esphome:
  name: zj_a1_ir
  platform: ESP8266
  board: esp_wroom_02

wifi:
  ssid: "homewifi"
  password: "homewifipass"

logger:

api:
  password: "zj_a1_ir"

ota:
  password: "zj_a1_ir"

status_led:
  pin: 
    number: GPIO4
    inverted: true

remote_receiver:
  pin: 
    number: GPIO5
    inverted: true
  dump: all

remote_transmitter:
  pin: 
    number: GPIO14
    inverted: false
  carrier_duty_percent: 50%
  id: "zj_a1_ir_transmitter"

# button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    internal: true
    name: "zj_a1_ir_button"
    id: "zj_a1_ir_button"

# restart esp on button click
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: restart_zj_a1_ir

 

switch:
  - platform: template
    name: "TV Panasonic On"
    turn_on_action:
      remote_transmitter.transmit_panasonic:
        address: 0x1FEF
        command: 0x1F3E065F