#Device Specific Config

switch:
  - platform: gpio
    pin: GPIO4
    name: "${friendly_name}"
    restore_mode: ALWAYS_OFF
    internal: true

binary_sensor:     

  - platform: gpio                     
    pin: GPIO5                              
    id: real_sensor_temp
    internal: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double Clicked"
          - lambda: |-
              if (id(template_sensor_2).state) {
              id(template_sensor_2).publish_state(false);
              } else {
              id(template_sensor_2).publish_state(true); 
              }
            
      - timing:
          - ON for 1s to 5s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Long Clicked"
          - lambda: |-
              if (id(template_sensor_3).state) {
              id(template_sensor_3).publish_state(false);
              } else {
              id(template_sensor_3).publish_state(true); 
              }

      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single Short Clicked"
          - lambda: |-
              if (id(template_sensor_1).state) {
              id(template_sensor_1).publish_state(false);
              } else { 
              id(template_sensor_1).publish_state(true);
              }
            

  - platform: template
    name: "${friendly_name} 1"
    id: template_sensor_1
  - platform: template
    name: "${friendly_name} 2"
    id: template_sensor_2
  - platform: template
    name: "${friendly_name} 3"
    id: template_sensor_3
