# Bluetooth Sniffer

# Variables
substitutions:
  device_name:    !secret node_3_device_name
  friendly_name:  !secret node_3_friendly_name
  hardware_id:    !secret node_3_hardware_id
  static_ip:      !secret node_3_static_ip
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml


esphome: 
  name: "${device_name}"
  name_add_mac_suffix: false
  platform: ESP32
  board: esp32dev
  build_path: "./.build/${device_name}/"
  
#esp32:
#  board: esp32dev
#  framework:
#    type: esp-idf
#    version: latest
#    sdkconfig_options:
#      CONFIG_FREERTOS_UNICORE: y


  
esp32_ble_tracker:
  scan_parameters:
    #interval: 30s
    #window: 30s
    active: false 

switch:
  - platform: safe_mode
    name: "Bluetooth Hub Restart (Safe Mode)"
  - platform: restart
    name: "Bluetooth Hub Restart"

sensor:
  - platform: ble_rssi
    mac_address: "A4:C1:38:BB:3C:AE"
    name: "Office Xiaomi BLE RSSI"
    
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:BB:3C:AE"
    temperature:
      name: "Office Temperature PVVX"
    humidity:
      name: "Office Humidity PVVX"
    battery_level:
      name: "Office Battery Level PVVX"
    battery_voltage:
      name: "Office Battery Voltage PVVX"

  - platform: ble_rssi
    mac_address: "A4:C1:38:52:8E:96"
    name: "Living Room Xiaomi BLE RSSI"
    
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:52:8E:96"
    temperature:
      name: "Living Room Temperature PVVX"
    humidity:
      name: "Living Room Humidity PVVX"
    battery_level:
      name: "Living Room Battery Level PVVx"
    battery_voltage:
      name: "Living Room Battery Voltage PVVX" 

  - platform: ble_rssi
    mac_address: "A4:C1:38:02:0C:B8"
    name: "Bedroom Xiaomi BLE RSSI"
    
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:02:0C:B8"
    temperature:
      name: "Bedroom Temperature PVVX"
    humidity:
      name: "Bedroom Humidity PVVX"
    battery_level:
      name: "Bedroom Battery Level PVVX"
    battery_voltage:
      name: "Bedroom Battery Voltage PVVX"
      
  - platform: ble_rssi
    mac_address: "A4:C1:38:3D:0B:5B"
    name: "Bathroom Xiaomi BLE RSSI"
    
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:3D:0B:5B"
    temperature:
      name: "Bathroom Temperature PVVX"
    humidity:
      name: "Bathroom Humidity PVVX"
    battery_level:
      name: "Bathroom Battery Level PVVX"
    battery_voltage:
      name: "Bathroom Battery Voltage PVVX"
      
  - platform: ble_rssi
    mac_address: "A4:C1:38:1C:9E:B6"
    name: "Hall Xiaomi BLE RSSI"
    
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:1C:9E:B6"
    temperature:
      name: "Hall Temperature PVVX"
    humidity:
      name: "Hall Humidity PVVX"
    battery_level:
      name: "Hall Battery Level PVVX"
    battery_voltage:
      name: "Hall Battery Voltage PVVX"
      
  - platform: ble_rssi
    mac_address: "A4:C1:38:F7:A7:65"
    name: "Fridge Xiaomi BLE RSSI"
    
  - platform: pvvx_mithermometer
    mac_address: "A4:C1:38:F7:A7:65"
    temperature:
      name: "Fridge Temperature PVVX"
    humidity:
      name: "Fridge Humidity PVVX"
    battery_level:
      name: "Fridge Battery Level PVVX"
    battery_voltage:
      name: "Fridge Battery Voltage PVVX"