# shelly_4_i3_mutual_remote

# Variables
substitutions:
  device_name:    !secret node_8_device_name
  friendly_name:  !secret node_8_friendly_name
  hardware_id:    !secret node_8_hardware_id
  static_ip:      !secret node_8_static_ip
  use_address:    !secret node_8_use_address
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

# Basic Config
esphome:
  name: $device_name
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/$device_name

wifi:
  use_address: $use_address
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet

packages:
  wifi: !include includes/network.yaml

#Device Specific Config

binary_sensor:

#Hall Light
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT
    name: Top $friendly_name
    id: sensorid1
    filters:
      - delayed_on_off: 80ms
      
#Kitchen Light
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT
    name: Mid $friendly_name
    id: sensorid2
    filters:
      - delayed_on_off: 80ms

#Living Room Light          
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT
      
    name: Bottom $friendly_name
    id: sensorid3
    filters:
      - delayed_on_off: 80ms

