# Office Wall Swich

# Variables
substitutions:
  device_name: !secret node_1_device_name
  friendly_name: !secret node_1_friendly_name
  hardware_id: !secret node_1_hardware_id
  static_ip: !secret node_1_static_ip
  gateway: !secret node_1_gateway
  subnet: !secret node_1_subnet
  use_address: !secret node_1_use_address

# Basic Config
esphome:
  name: "${device_name}"
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/${device_name}
  
wifi:
  use_address: $use_address
  manual_ip:
    static_ip: $static_ip
    gateway: $gateway
    subnet: $subnet

packages:
  #Wifi Settings
  wifi: !include includes/network.yaml

#Device Specific Config

switch:
  - platform: gpio
    pin: GPIO4
    name: "${friendly_name}"
    restore_mode: ALWAYS_OFF
    internal: true

binary_sensor:                         
  - platform: gpio                     
    pin: GPIO5                              
    name: "${friendly_name}"