# bedroom_yeelight_ceiling

# Variables
substitutions:
  device_name:    !secret node_5_device_name
  friendly_name:  !secret node_5_friendly_name
  hardware_id:    !secret node_5_hardware_id
  static_ip:      !secret node_5_static_ip
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml    
  board:  !include includes/boards/xiaomi_ceiling.yaml
  device: !include includes/devices/bedroom_ceiling.yaml
