# Bluetooth Sniffer

# Variables
substitutions:
  device_name:    !secret node_3_device_name
  friendly_name:  !secret node_3_friendly_name
  hardware_id:    !secret node_3_hardware_id
  static_ip:      !secret node_3_static_ip
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml
  board:  !include includes/boards/esp32dev.yaml
  device: !include includes/devices/bluetooth_sniffer.yaml
