# socket_multi_office_desk

# Variables
substitutions:
  device_name:    !secret node_16_device_name
  friendly_name:  !secret node_16_friendly_name
  hardware_id:    !secret node_16_hardware_id
  static_ip:      !secret node_16_static_ip
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml
  board:  !include includes/boards/esp8285.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: false
    name: "${friendly_name} Button"
    internal: true 
    
switch:
  - platform: gpio
    name: "${friendly_name} Nubert"
    pin: GPIO05
    id: nubert
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} Display"
    pin: GPIO04
    id: display
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} PC"
    pin: GPIO12
    id: macbook
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} Desk"
    pin: GPIO13
    id: desk
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} USB"
    pin: GPIO14
    id: usb
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} LED"
    pin: GPIO01
    restore_mode: ALWAYS_OFF
    internal: true