# shelly_6_25_bathroom

# Variables
substitutions:
  device_name:    !secret node_19_device_name
  friendly_name:  !secret node_19_friendly_name
  hardware_id:    !secret node_19_hardware_id
  static_ip:      !secret node_19_static_ip
  channel_1:      !secret node_19_channel_1
  channel_2:      !secret node_19_channel_2
  remote_2:       !secret node_19_remote_2
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml
  device: !include includes/devices/shelly_25.yaml
  board:  !include includes/boards/esp01_1m.yaml

fan:
  - platform: binary
    output: out_channel_2
    name: $channel_2
    id: channel_2

light:
  - platform: binary
    name: "${channel_1}"
    restore_mode: RESTORE_DEFAULT_OFF
    output: out_channel_1
    id: channel_1

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    name: "${channel_1}"
    on_state:
      then:
        - light.toggle: channel_1
    internal: true

  - platform: gpio
    pin:
      number: GPIO5
    name: "${remote_2}"
    on_state:
      # Simple
      - homeassistant.event:
          event: esphome.ws_remote
          data:
            title: flip

