# shelly_6_25_bathroom

# Variables
substitutions:
  device_name:    !secret node_19_device_name
  friendly_name:  !secret node_19_friendly_name
  hardware_id:    !secret node_19_hardware_id
  static_ip:      !secret node_19_static_ip
  channel_1:      !secret node_19_channel_1
  channel_2:      !secret node_19_channel_2
  remote_2:       !secret node_19_remote_2
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml
  device: !include includes/devices/shelly_25_bathroom.yaml
