# shelly_3_guest_wc

# Variables
substitutions:
  device_name:    !secret node_7_device_name
  friendly_name:  !secret node_7_friendly_name
  hardware_id:    !secret node_7_hardware_id
  static_ip:      !secret node_7_static_ip
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml
  device: !include includes/devices/shelly_1_flip_remote.yaml

    