#Variables
substitutions:
  device_name: shelly_01_bathroom_remote
  friendly_name: Bahtroom Shelly Remote
  
# Basic Config
esphome:
  name: "${device_name}"
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/${device_name}
  
#Wifi
wifi:
  networks:
  - ssid: "TP-LINK MAX"
    password: "internet!"
  # If wifi can not connect reboot with in xx hours  
  reboot_timeout: 24h
  fast_connect: true

  #Access Point
  ap:
    ssid: "${device_name}"
    password: !secret wifi_ap_password

#Captive Portal when ap is on
captive_portal:

#Web Server for manual access 
web_server:

#Log to ESPHome
logger:
  #Disable logging to serial
  baud_rate: 0  

#Homeassitant API
api:
  reboot_timeout: 24h

#ESPHome OTA
ota:
  

#Device Specific Config

switch:
  - platform: gpio
    pin: GPIO4
    name: "${friendly_name}"
    restore_mode: RESTORE_DEFAULT_ON
    internal: true
    id: relay


binary_sensor:                         
  - platform: gpio                     
    pin: GPIO5                              
    name: "${friendly_name}"
    on_state:
      if:
        condition:
          not:
            api.connected:
        then:
          - switch.toggle: relay




