# socket_multi_office_desk

# Variables
substitutions:
  device_name:    !secret node_16_device_name
  friendly_name:  !secret node_16_friendly_name
  hardware_id:    !secret node_16_hardware_id
  static_ip:      !secret node_16_static_ip
  ssid:           !secret not_ssid
  ssid_pw:        !secret not_password
  ap_pw:          !secret ap_password 
  gateway:        !secret not_gateway
  subnet:         !secret not_subnet
  ntp:            !secret ntp

wifi:
  <<: !include includes/network_manual_ip.yaml

packages:
  wifi:   !include includes/network.yaml

esphome:
  <<: !include .esphome.yaml
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: false
    name: "${friendly_name} Button"
    internal: true
    on_click:
    - min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: sw_4
        - switch.turn_on: sw_3
        - switch.turn_on: sw_2
        - switch.turn_on: sw_1    
    - min_length: 500ms
      max_length: 1000ms
      then:
        - switch.turn_off: sw_4
        - switch.turn_off: sw_3
        - switch.turn_off: sw_2
        - switch.turn_off: sw_1 
    
switch:
  - platform: gpio
    name: "${friendly_name} 4"
    pin: GPIO05
    id: sw_4
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        - delay: 2hours
        - switch.turn_off: sw_4
  - platform: gpio
    name: "${friendly_name} 3"
    pin: GPIO04
    id: sw_3
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} 2"
    pin: GPIO12
    id: sw_2
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} 1"
    pin: GPIO13
    id: sw_1
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} USB"
    pin: GPIO14
    id: usb
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${friendly_name} LED"
    pin: GPIO01
    restore_mode: ALWAYS_OFF
    internal: true